brain_two/urls.py
from django.contrib import admin
from django.urls import path
from todos.views import TodoListView, TodoDetailView
from django.views.generic.base import RedirectView
from todos.views import TodoCreateView
from todos.views import TodoUpdateView
from todos.views import TodoDeleteView
from todos.views import TodoItemCreateView
from todos.views import TodoitemUpdateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("todos/", TodoListView.as_view(), name="list_todos"),
    path("todos/<int:pk>/edit", TodoUpdateView.as_view(), name="update_todolist"),
    path("", RedirectView.as_view(url="/todos")),
    path("<int:pk>/", TodoDetailView.as_view(), name="todo_list_detail"),
    path("create/", TodoCreateView.as_view(), name="create_todolist"),
    path("<int:pk>/delete", TodoDeleteView.as_view(), name="delete_todolist"),
    path("items/create/", TodoItemCreateView.as_view(), name="create_todoitem"),
    path("todos/items/<int:pk>/edit", TodoitemUpdateView.as_view(), name="update_todoitem")
]

todos/urls.py
from django.urls import path

from todos.views import TodoListView
from todos.views import TodoDetailView
from todos.views import TodoCreateView
from todos.views import TodoUpdateView
from todos.views import TodoDeleteView
from todos.views import TodoItemCreateView
from todos.views import TodoitemUpdateView

urlpatterns = [
    path("", TodoListView.as_view(), name="list_todos"),
    path("todos/", TodoListView.as_view(), name="list_todos"),
    path("<int:pk>/", TodoDetailView.as_view(), name="todo_list_detail"),
    path("create/", TodoCreateView.as_view(), name="create_todolist"),
    path("/todos/<int:pk>/edit", TodoUpdateView.as_view(), name="update_todolist"),
    path("<int:pk>/delete/",TodoDeleteView.as_view(),name="delete_todolist"),
    path("items/create/", TodoItemCreateView.as_view(), name="create_todoitem"),
    path("todos/items/<int:pk>/edit", TodoitemUpdateView.as_view(), name="update_todoitem") 
]

todos/models.py
from django.db import models

# Create your models here.

class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList", related_name="items", on_delete=models.CASCADE
    )

todos/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from todos.models import TodoItem, TodoList
from django.urls import reverse_lazy

# Create your views here.

class TodoListView(ListView):
    model = TodoList
    template_name = "list.html"


class TodoDetailView(DetailView):
    model = TodoList
    template_name = "detail.html"

class TodoCreateView(CreateView):
    model = TodoList
    template_name = "create.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy('todo_list_detail', args=[self.object.id])

class TodoUpdateView(UpdateView):
    model = TodoList
    template_name = 'update.html'
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy('todo_list_detail', args=[self.object.id])


class TodoDeleteView(DeleteView):
    model = TodoList
    template_name = "delete.html"
    success_url = reverse_lazy("list_todos")


class TodoItemCreateView(CreateView):
    model = TodoItem
    template_name = "todoitem/create.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.list.id])


class TodoitemUpdateView(UpdateView):
    model = TodoItem
    template_name = "todoitem/update.html"
    fields = ["task", "Due date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.list.id])

todos/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Todo Lists</title>
  </head>
  <body>
    {% block content %} {% endblock content %}
  </body>
</html>

todos/templates/create.html
{% extends 'base.html' %}
{% block content %}
    <main>
      <div>
        <h1>Create a new list</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Submit</button>
      </div>
    </main>
{% endblock content %}

todos/templates/delete.html
{% extends 'base.html' %} {% block content %}

<main>
  <div>
    <h1>Are you sure?</h1>
    <form method="POST">
      {% csrf_token %} {{ form.as_p }}
      <button>Delete</button>
    </form>
  </div>
</main>

{% endblock content %}

todos/templates/detail.html
{% extends 'base.html' %} {% block content %}
<main>
  <div>
    <h1>{{ todolist.name }}</h1>
    <p><a href="{% url 'update_todolist' todolist.id %}">Edit</a></p>
    <p><a href="{% url 'delete_todolist' todolist.id %}">Delete</a></p>
    <h2>Tasks</h2>
    <table>
      <thead>
        <tr>
          <th>Task</th>
          <th>Due date</th>
        </tr>
      </thead>
      <tbody>
        {% for item in todolist.items.all %}
        <tr>
          <td>
            <a href="{% url 'todo_list_detail' item.id %}">{{ item.task }}</a>
          </td>
          <td>{{ item.due_date|date:"M d, Y" }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</main>
{% endblock content %}

todos/templates/list.html
{% extends 'base.html' %} {% block content %}
<main>
  <div>
    <h1>My Lists</h1>
    <p>
      <a href="{% url 'create_todolist' %}">Create a new list</a>
    </p>
    <p><a href="{% url 'create_todoitem' %}">Create a new item</a></p>
    <table>
      <thead>
        <th>Name</th>
        <th>Number of items</th>
      </thead>
      <tbody>
        {% for list_name in todolist_list %}
        <tr>
          <td>
            <a href="{% url 'todo_list_detail' list_name.id %}"
              >{{ list_name }}
            </a>
          </td>
          <td>{{list_name.items.all|length}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</main>
{% endblock content %}

todos/templates/todoitem/create.html
{% extends 'base.html' %} {% block content %}
<main>
  <div>
    <h1>Create a new item</h1>
    <form method="post">
      {% csrf_token %} {{ form.as_p }}
      <button>Submit</button>
    </form>
  </div>
</main>
{% endblock content %}

todos/templates/todoitem/update.html
{% extends 'base.html' %} {% block content %}

<main>
  <div>
    <h1>Update item</h1>
    <form method="POST">
      {% csrf_token %} {{ form.as_p }}
      <button>Update</button>
    </form>
  </div>
</main>

todos/templates/update.html
{% extends 'base.html' %} {% block content %}
<main>
  <div>
    <h1>Update List</h1>
    <form method="POST">
      {% csrf_token %} {{ form.as_p }}
      <button>Update</button>
    </form>
  </div>
</main>
{% endblock content %}